# Generated by Django 4.0.6 on 2022-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapi', '0002_review_delete_genre_remove_books_review_books_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
